In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("/content/drive/MyDrive/Python Programs/healthcare_dataset.csv")
df

,Patient_ID,Gender,Age,Medical_Condition,Admission_Date,Admission_Type,Medical_Code,Billing_Amount,Discharge_Date
0,P1001,Male,45,Hypertension,15-01-2026,Urgent,ICD-10-I10,4500.0,20-01-2026
1,P1002,Female,32,Pneumonia,16-01-2026,Emergency,ICD-10-J18,6700.5,22-01-2026
2,P1003,Male,68,Diabetes Type 2,16-01-2026,Routine,ICD-10-E11,3200.0,18-01-2026
3,P1004,Female,55,Asthma,17-01-2026,Emergency,ICD-10-J45,5800.0,19-01-2026
4,P1005,Male,29,Fracture,17-01-2026,Urgent,ICD-10-S52,8500.0,25-01-2026
...,...,...,...,...,...,...,...,...,...
495,P1496,Female,50,COPD,20-09-2026,Emergency,ICD-10-J44,9800.0,23-09-2026
496,P1497,Male,28,Fracture,20-09-2026,Urgent,ICD-10-S52,9400.0,24-09-2026
497,P1498,Female,67,Heart Attack,21-09-2026,Emergency,ICD-10-I21,14200.0,25-09-2026
498,P1499,Male,43,Diabetes Type 2,21-09-2026,Routine,ICD-10-E11,4900.0,23-09-2026
499,P1500,Female,61,Stroke,22-09-2026,Emergency,ICD-10-I63,13900.0,26-09-2026

In [5]:
print(df.head())

  Patient_ID  Gender  Age Medical_Condition Admission_Date Admission_Type  \
0      P1001    Male   45      Hypertension     15-01-2026         Urgent
1      P1002  Female   32         Pneumonia     16-01-2026      Emergency
2      P1003    Male   68   Diabetes Type 2     16-01-2026        Routine
3      P1004  Female   55            Asthma     17-01-2026      Emergency
4      P1005    Male   29          Fracture     17-01-2026         Urgent

  Medical_Code  Billing_Amount Discharge_Date
0   ICD-10-I10          4500.0     20-01-2026
1   ICD-10-J18          6700.5     22-01-2026
2   ICD-10-E11          3200.0     18-01-2026
3   ICD-10-J45          5800.0     19-01-2026
4   ICD-10-S52          8500.0     25-01-2026

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Patient_ID         500 non-null    object
 1   Gender             500 non-null    object
 2   Age                500 non-null    int64
 3   Medical_Condition  500 non-null    object
 4   Admission_Date     500 non-null    object
 5   Admission_Type     500 non-null    object
 6   Medical_Code       500 non-null    object
 7   Billing_Amount     500 non-null    float64
 8   Discharge_Date     500 non-null    object
dtypes: float64(1), int64(1), object(7)
memory usage: 35.3+ KB

In [7]:
df['Admission_Date'] = pd.to_datetime(df['Admission_Date'], format='%d-%m-%Y')
df['Discharge_Date'] = pd.to_datetime(df['Discharge_Date'], format='%d-%m-%Y')

In [8]:
print(df.isnull().sum())

Patient_ID           0
Gender               0
Age                  0
Medical_Condition    0
Admission_Date       0
Admission_Type       0
Medical_Code         0
Billing_Amount       0
Discharge_Date       0
dtype: int64

In [9]:
df = df.dropna()

In [10]:
df = df.drop_duplicates()
df

,Patient_ID,Gender,Age,Medical_Condition,Admission_Date,Admission_Type,Medical_Code,Billing_Amount,Discharge_Date
0,P1001,Male,45,Hypertension,2026-01-15,Urgent,ICD-10-I10,4500.0,2026-01-20
1,P1002,Female,32,Pneumonia,2026-01-16,Emergency,ICD-10-J18,6700.5,2026-01-22
2,P1003,Male,68,Diabetes Type 2,2026-01-16,Routine,ICD-10-E11,3200.0,2026-01-18
3,P1004,Female,55,Asthma,2026-01-17,Emergency,ICD-10-J45,5800.0,2026-01-19
4,P1005,Male,29,Fracture,2026-01-17,Urgent,ICD-10-S52,8500.0,2026-01-25
...,...,...,...,...,...,...,...,...,...
495,P1496,Female,50,COPD,2026-09-20,Emergency,ICD-10-J44,9800.0,2026-09-23
496,P1497,Male,28,Fracture,2026-09-20,Urgent,ICD-10-S52,9400.0,2026-09-24
497,P1498,Female,67,Heart Attack,2026-09-21,Emergency,ICD-10-I21,14200.0,2026-09-25
498,P1499,Male,43,Diabetes Type 2,2026-09-21,Routine,ICD-10-E11,4900.0,2026-09-23
499,P1500,Female,61,Stroke,2026-09-22,Emergency,ICD-10-I63,13900.0,2026-09-26

In [11]:
df['Admission_Type'] = df['Admission_Type'].str.strip().str.title()
df['Admission_Category'] = df['Admission_Type'].replace({'Routine': 'Elective'})
admission_category_counts = df['Admission_Category'].value_counts()
print(admission_category_counts)

Admission_Category
Elective     196
Emergency    188
Urgent       116
Name: count, dtype: int64

In [12]:
df["Hospital_Stays"] = (df["Discharge_Date"] - df["Admission_Date"]).dt.days
Hospital_Stays_Summary = df['Hospital_Stays'].describe()
print(Hospital_Stays_Summary)

count    500.00000
mean       2.74400
std        1.17696
min        1.00000
25%        2.00000
50%        2.00000
75%        4.00000
max       10.00000
Name: Hospital_Stays, dtype: float64

In [13]:
Billing_Amount_Summary = df['Billing_Amount'].describe()
print(Billing_Amount_Summary)

count      500.00000
mean      7249.00100
std       3198.96932
min       2300.00000
25%       4400.00000
50%       6950.00000
75%       9400.00000
max      14200.00000
Name: Billing_Amount, dtype: float64

In [14]:
medical_condition_counts = df['Medical_Condition'].value_counts()
print(medical_condition_counts)

Medical_Condition
COPD                       34
Appendicitis               33
Stroke                     33
Pneumonia                  31
Heart Failure              30
Kidney Stone               28
Hypertension               28
Heart Attack               27
Fracture                   22
Gastritis                  21
Skin Infection             20
Back Pain                  20
Asthma                     19
Parkinson's Disease        19
Urinary Tract Infection    18
Pregnancy                  16
Diabetes Type 2            16
Allergic Reaction          15
Gallstones                 15
Diabetes Type 1            15
Osteoporosis               12
Osteoarthritis             12
Anxiety Disorder            9
Migraine                    6
Hypothyroidism              1
Name: count, dtype: int64

In [15]:
medical_condition_gender_crosstab = pd.crosstab(df['Medical_Condition'], df['Gender'])
print(medical_condition_gender_crosstab)

Gender                   Female  Male
Medical_Condition
Allergic Reaction            14     1
Anxiety Disorder              2     7
Appendicitis                  8    25
Asthma                        8    11
Back Pain                     5    15
COPD                         16    18
Diabetes Type 1              12     3
Diabetes Type 2               6    10
Fracture                      7    15
Gallstones                    3    12
Gastritis                    11    10
Heart Attack                 15    12
Heart Failure                10    20
Hypertension                 19     9
Hypothyroidism                1     0
Kidney Stone                 10    18
Migraine                      6     0
Osteoarthritis                6     6
Osteoporosis                  8     4
Parkinson's Disease           9    10
Pneumonia                    18    13
Pregnancy                    14     2
Skin Infection               12     8
Stroke                       16    17
Urinary Tract Infection      14     4

In [16]:
medical_condition_age_summary = df.groupby('Medical_Condition')['Age'].mean()
print(medical_condition_age_summary)

Medical_Condition
Allergic Reaction          33.400000
Anxiety Disorder           37.111111
Appendicitis               33.090909
Asthma                     41.894737
Back Pain                  40.650000
COPD                       65.176471
Diabetes Type 1            50.200000
Diabetes Type 2            52.375000
Fracture                   38.909091
Gallstones                 49.066667
Gastritis                  40.047619
Heart Attack               65.925926
Heart Failure              64.433333
Hypertension               53.392857
Hypothyroidism             52.000000
Kidney Stone               49.000000
Migraine                   30.500000
Osteoarthritis             53.166667
Osteoporosis               54.166667
Parkinson's Disease        72.631579
Pneumonia                  57.709677
Pregnancy                  29.187500
Skin Infection             33.150000
Stroke                     63.242424
Urinary Tract Infection    43.777778
Name: Age, dtype: float64